### ISSUE TITLE
Issues running under AGP 4.0.1 and 4.2.2

### ISSUE THREAD

**Issue by mattinger** [MarathonLabs/marathon#543]
Project Setup:

Gradle 6.7.1
AGP 4.0.1/4.2.2
Kotlin 1.5.20

When i'm trying to run marathon under those conditions, i'm getting the following error

java.lang.NoSuchMethodError: kotlinx.coroutines.channels.ChannelKt.Channel$default(ILkotlinx/coroutines/channels/BufferOverflow;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lkotlinx/coroutines/channels/Channel;
Finish BugSnag

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:marathonComcastDebugAndroidTest'.
> Tests failed! See /....

the resulting stack trace and debug logs don't really reveal anything useful.

Caused by: org.gradle.api.GradleException: Tests failed! See .../index.html
        at com.malinskiy.marathon.MarathonRunTask.runMarathon(MarathonRunTask.kt:127)
I suspect it's the NoSuchMethodError that is the issue.

The odd part is that it works fine with AGP 7.0.0 and kotlin 1.5.20

**Comment by mattinger** [comment]
Looking at MarathonRunner, it seems like the error is actually just getting swallowed and a "Tests Failed" message is output at the indicated line above.  I can also tell from the logcat that the app is never even getting deployed to the VM.

**Comment by mattinger** [comment]
Further debugging puts the issue here:

```
declaringClass = "com.malinskiy.adam.transport.vertx.VertxSocketKt"
methodName = "toChannel"
fileName = "VertxSocket.kt"
lineNumber = 214
```

**Comment by Malinskiy** [comment]
Hey @mattinger, thanks for submitting this!

This particular problem you're experiencing is due to the fact that your build controls the classpath of marathon execution and it looks like the version of coroutines in your classpath is different to the one used by marathon. Please read the section on [choosing the distribution](https://marathonlabs.github.io/marathon/doc/downloading.html#choosing-the-distribution) of marathon.

You may be able to get around this error by forcing a particular version of coroutines via buildscript classpath (e.g. https://github.com/MarathonLabs/marathon/blob/develop/sample/android-app/build.gradle.kts#L17), but that still doesn't provide any guarantee whatsoever if your environment didn't upgrade some library that marathon depends on.

**Comment by trevjonez** [comment]
this is probably a good  candidate for moving to gradle worker api so we could use the class loader or process isolation feature of it.
https://docs.gradle.org/current/userguide/worker_api.html#changing_the_isolation_mode

**Comment by mattinger** [comment]
FYI @Malinskiy I switched to DDMLIB and it seems to work, so it's definitely localized to ADAM

**Comment by Malinskiy** [comment]
@trevjonez this was considered before, but due to previous experience with this API it was rejected as an option. We currently plan to rework the gradle plugin to call out to CLI (hence for the JVM). This should provide full control over classpath

@mattinger thanks for highlighting this. ddmlib doesn't use coroutines, hence you don't have classpath conflict (adam uses coroutines extensively). From the error it is highly likely that you have coroutines 1.3.X and marathon + adam depends on 1.4.X

**Comment by mattinger** [comment]
@Malinskiy I'm running gradle 6.7.1 with the kotlin gradle plugin version 1.5.20.  Unfortunately it seems they have messed up the dependencies for that compiler and it depends on the wrong version of coroutines.

as reported by `./gradlew buildEnvironment`

```
|    +--- org.jetbrains.kotlin:kotlin-compiler-runner:1.5.20
|    |    +--- org.jetbrains.kotlin:kotlin-build-common:1.5.20
|    |    +--- org.jetbrains.kotlin:kotlin-daemon-client:1.5.20
|    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.8
|    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.8
|    |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.5.20 (*)
```

I will try forcing it to the 1.5 version of coroutines and see what happens.

**Comment by mattinger** [comment]
I tried forcing it into other versions of coroutines library in the buildscript classpath, but it didn't work.

```
java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException
```

**Comment by Malinskiy** [comment]
That's exactly why the usage of gradle plugin is discouraged in the docs: we can't control your classpath. I suggest you try out the CLI version since your classpath is outside of our control at the moment. In the future, it might be possible to use gradle plugin safely (tracked in #442), but we don't have anyone working on that right now. If you wish to help with the development - please reach out to me via slack

**Comment by Malinskiy** [comment]
Closed in 0.7.0 by #573
